import { ClerkProvider } from "@clerk/nextjs";
import SideBar from "@/components/SideBar";
import "../../../app/globals.css";
import { Urbanist } from "next/font/google";
import classNames from "classnames";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Favcy Navigator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={classNames({
          [`${urbanist.className}`]: true,
        })}
      >
        {/* <ClerkProvider> */}
        <section className="max-w-7xl w-full mx-auto p-10 h-screen">{children}</section>
        {/* </ClerkProvider> */}
      </body>
    </html>
  );
}
