"use client";

import { ClerkProvider } from "@clerk/nextjs";
import SideBar from "@/components/SideBar";
import "./globals.css";
import { Urbanist } from "next/font/google";

import ParentLayout from "@/components/ParentLayout";
import { ToastContainer } from "react-toastify";
import { RecoilRoot } from "recoil";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const metadata = {
  title: "Favcy Navigator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Favcy Navigator</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <RecoilRoot>{children}</RecoilRoot>
      </body>
    </html>
  );
}
