"use client";

import SideBar from "@/components/SideBar";
import "./globals.css";
import { Inter, Urbanist } from "next/font/google";
import { useState } from "react";
import classNames from "classnames";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Favcy Navigator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [collapsed, setSidebarCollapsed] = useState(false);
  return (
    <html lang="en">
      <body
        className={classNames({
          "grid min-h-screen ": true,
          "grid-cols-sidebar": !collapsed,
          "grid-cols-sidebar-collapsed": collapsed,
          "transition-[grid-template-columns] duration-300 ease-in-out": true,
          [`${urbanist.className}`]: true,
        })}
      >
        <SideBar collapsed={collapsed} setCollapsed={setSidebarCollapsed} />
        <section>{children}</section>
      </body>
    </html>
  );
}
