import "../globals.css";
import { Urbanist } from "next/font/google";

import ParentLayout from "@/components/ParentLayout";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Favcy Navigator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    <div>
      <ParentLayout>{children}</ParentLayout>
    </div>
    // </html>
  );
}
